#!/bin/bash

# bash_profile


# add ssh_key

DOTFILES_DIRECTORY="${HOME}/dvp/dotfiles"

SSH_KEY_PATH="${HOME}/dvp/ssh/private.pem"

if [ -z "$SSH_AUTH_SOCK" ] ; then
  eval `ssh-agent -s`
  ssh-add $SSH_KEY_PATH
fi


# set 256 color profile where possible
if [[ $COLORTERM == gnome-* && $TERM == xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
    export TERM=gnome-256color
elif infocmp xterm-256color >/dev/null 2>&1; then
    export TERM=xterm-256color
fi


load_dotfiles() {
    declare -a files=(
        $DOTFILES_DIRECTORY/shell/bash_options # Options
        $DOTFILES_DIRECTORY/shell/bash_exports # Exports
        $DOTFILES_DIRECTORY/shell/bash_aliases # Aliases
        $DOTFILES_DIRECTORY/shell/bash_prompt # Custom bash prompt
        $DOTFILES_DIRECTORY/shell/bash_paths # Path modifications
        $(brew --prefix)/etc/bash_completion # Bash completion (installed via Homebrew)
        $HOME/.bash_profile.local # Local and private settings not under version control (e.g. git credentials)
    )

    # if these files are readable, source them
    for index in ${!files[*]}
    do
        if [[ -r ${files[$index]} ]]; then
            source ${files[$index]}
        fi
    done
}

load_dotfiles
unset load_dotfiles
